# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Permalinks
permalink:           pretty

# Setup
url:                 http://qwtel.com

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl:             ''

title:               PJ Hampton 

# Pagination
paginate:            5
paginate_path:       '/page-:num/'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         >
  Developer & Researcher

# The tags listed as entries in the sidebar
sidebar_tags:        [jekyll, hyde]

# Fallback image and color if not overwritten for tag or post
image:               /hydejack/public/img/nap.jpg
color:               '#A85641'

# Fonts
font:                '"PT Serif", Georgia, serif'
font_accent:         '"Roboto Slab", "PT Serif", Georgia, serif'
load_google_fonts:   'Roboto+Slab:700|PT+Serif:400,400italic,700,700italic'

# About yourself
author:
  name:              'PJ Hampton'

  # Social media icons in sidebar
  # Comment/uncommet to show/hide
  # Icons appear in order, can be rearranged:
  social:
    twitter:           pjhampt0n
    # youtube:         _string___string___string_
    instagram:         pjhampton 
    github:            pjhampton
    stackoverflow:     3968703/ham-sandwich
    linkedin:          pjhampton

# Setting a disqus subdomain will enable the comment section
# disqus:            <username>

kramdown:
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed
